services:
  frontend:
    container_name: spots-frontend
    restart: unless-stopped 
    env_file: ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run start
    networks:
      - web

  backend:
    container_name: spots-backend
    restart: unless-stopped 
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - web
networks:
  web:
